docs: adding Design & Implementation #1329
GluuFederation/flex pull request #1330
Opened 2023-09-16 15:22 UTC by duttarnab

closes #1329

2023-09-18 10:50 UTC, ossdhaval requested changes

2023-09-18 10:50 UTC, ossdhaval commented on docs/assets/admin-ui/design-access-config-api.png
@duttarnab please use `mermaid` to code the sequence diagrams. You can follow the example [here](https://docs.jans.io/v1.0.16/contribute/implementation-design/jans-config-api/)

2023-09-18 15:39 UTC, duttarnab commented on docs/assets/admin-ui/design-access-config-api.png
done

2023-09-19 08:31 UTC, ossdhaval approved these changes

2023-09-19 08:32 UTC, merged