docs: add details to Flex readme
GluuFederation/flex pull request #1479
Opened 2023-11-27 11:23 UTC by ossdhaval

closes #1332

2023-11-27 11:37 UTC, ossdhaval commented
@nynymike @moabu 

I have put the initial content on the README. Some of these are from the Flex home page on [gluu.org](gluu.org). This is to keep the messaging consistent between the home page and the README. Also, as discussed, I have highlighted important aspects of admin-ui, which essentially is the differentiator between Jans and Flex. 

More can be added:
1. Detailed aspects of Admin UI. But this will overlap with admin-ui documentation for which the link is given on the README.
2. Details about some of the important features provided by Janssen like cloud-native deployments, Agama, etc.

Let me know your thoughts and suggestions.

**A quick question**: 

Does the Flex license enable more features in Agama Lab? If yes, then we should highlight those also. Because that feature becomes part and parcel of Flex. I think the ability to host the Agama project in the GH private repo is one such feature. Is it? Are there more such features?

2023-11-27 13:32 UTC, moabu requested changes

2023-11-27 13:32 UTC, moabu commented on README.md
> +open source distribution is easy–just update your configuration.
fix easy-just typo. Its actually a simple two way pathway. Once you have flex you can move back with unsubscribing to the admin UI and any support contract.

2023-11-28 11:27 UTC, ossdhaval commented
Putting @nynymike's comments from chat:

![image](https://github.com/GluuFederation/flex/assets/343411/148864d9-4240-4723-902d-170712e3ce70)

2023-11-29 10:59 UTC, moabu approved these changes

2023-11-29 10:59 UTC, merged