fix(docs): add clarity about SSA and license
GluuFederation/flex pull request #1485
Opened 2023-11-30 07:00 UTC by ossdhaval

2023-11-30 08:28 UTC, moabu requested changes

2023-11-30 08:28 UTC, moabu commented on README.md
> +more SSAs issued for a particular license using Agama Lab.
I would add a link to the Agama lab

2023-11-30 11:25 UTC, ossdhaval commented on README.md
> +more SSAs issued for a particular license using Agama Lab.
added.

2023-12-05 09:09 UTC, moabu approved these changes

2023-12-05 09:09 UTC, merged