feat(flex-linux-setup): use built archive for setup
GluuFederation/flex pull request #1733
Opened 2024-05-29 17:54 UTC by devrimyatar

closes #1725

2024-05-29 19:08 UTC, iromli approved these changes

2024-05-29 19:16 UTC, iromli requested changes

2024-05-29 19:16 UTC, iromli commented on flex-linux-setup/flex_linux_setup/templates/env-config.js
> +const BASE_PATH = "/admin"
we can use `BASE_PATH=/admin/` now as the main issue in cloud-native has been resolved.

2024-05-30 17:08 UTC, duttarnab approved these changes

2024-05-31 09:14 UTC, merged