feat(charts): add pod level annotations and customizable command
GluuFederation/flex pull request #1854
Opened 2024-10-11 17:41 UTC by misba7

closes #1843

2024-10-24 19:16 UTC, iromli requested changes

2024-10-24 19:16 UTC, iromli commented on charts/gluu-all-in-one/values.yaml
> +  # command:
It would be best to show the generated `command` instead of Helm's templating.

2024-10-24 19:17 UTC, iromli commented
@misba7 Please update the PR so it won't have conflict with `main` branch. Also generate the docs.

2024-10-25 18:18 UTC, moabu approved these changes

2024-10-25 18:19 UTC, merged