feat(admin-ui): allow users to install Agama Lab community projects from Admin UI
GluuFederation/flex pull request #1862
Opened 2024-10-21 05:23 UTC by mjatin-dev

closes [1846](https://github.com/GluuFederation/flex/issues/1846)

2024-11-06 10:47 UTC, duttarnab commented
This PR is on hold. It can be addressed once the APIs are available . Issue raised for API development: `https://github.com/JanssenProject/jans/issues/9907`.

2025-01-08 07:54 UTC, duttarnab requested changes
Please see inline comments

2025-01-08 07:54 UTC, duttarnab commented on admin-ui/plugins/auth-server/redux/api/AgamaApi.js
> +      axios.post('/api/v1/agama-deployment/' + name, file, {
we should use jans-config-api client for calling apis.

2025-01-08 07:54 UTC, duttarnab commented on admin-ui/plugins/auth-server/components/Agama/AgamaListPage.js
> +} from "../../redux/features/agamaSlice";
we should use alias here for example: https://github.com/GluuFederation/flex/blob/main/admin-ui/plugins/auth-server/components/Agama/AgamaListPage.js#L28C32-L28C66

2025-01-09 17:40 UTC, mjatin-dev commented on admin-ui/plugins/auth-server/redux/api/AgamaApi.js
> +      axios.post('/api/v1/agama-deployment/' + name, file, {
@duttarnab Yes, we could, but I encountered an error with the jans-config-api because we are using a string. That's why we are opting for Axios instead.

2025-01-09 19:20 UTC, duttarnab approved these changes

2025-01-09 19:20 UTC, merged