added helm test
GluuFederation/flex pull request #555
Opened 2022-10-27 12:38 UTC by himanshu2464

2022-10-28 07:21 UTC, moabu requested changes
Although these work the response back from them aren't entirely accurate. Some of these endpoints return a dictionary object showing the database status as well. Think of a way to call the python script listed in to execute the parse of these. Also think about adding a test connection for the database as well.

2022-10-28 07:21 UTC, moabu commented on flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/charts/admin-ui/values.yaml
> -  name: http-admin-ui
do not change these

2022-10-28 07:21 UTC, moabu commented on flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/charts/auth-server/values.yaml
> -  name: http-auth
do not change these

2022-10-28 07:21 UTC, moabu commented on flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/charts/config-api/values.yaml
> -  name: http-config-api
do not change these

2022-10-28 20:41 UTC, himanshu2464 commented on flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/charts/auth-server/values.yaml
> -  name: http-auth
okay

2022-10-28 20:41 UTC, himanshu2464 commented on flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/charts/config-api/values.yaml
> -  name: http-config-api
okay

2022-10-28 20:43 UTC, himanshu2464 commented
> Although these work the response back from them aren't entirely accurate. Some of these endpoints return a dictionary object showing the database status as well.
> 
> * [ ]  Think of a way to call the python script listed in to execute the parse of these.
> * [ ]  Think about adding a test connection for the database as well. Hint: its already included in one of the services.
> * [ ]   Add a workflow that executes testing it

okay, we can add the script to check the database connection and also a python or bash script.

2022-10-31 08:36 UTC, moabu commented
> > Although these work the response back from them aren't entirely accurate. Some of these endpoints return a dictionary object showing the database status as well.
> > 
> > * [ ]   Think of a way to call the python script listed in to execute the parse of these.
> > * [ ]   Think about adding a test connection for the database as well. Hint: its already included in one of the services.
> > * [ ]    Add a workflow that executes testing it
> 
> okay, we can add the script to check the database connection and also a python or bash script. and ya sure I will add the workflow to execute testing it.

Think in terms of what already exists in the containers  https://github.com/GluuFederation/flex/blob/main/flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/values.yaml#L187

2023-07-24 04:07 UTC, closed without merging