feat(admin-ui): create authn option under Auth Server menu.
GluuFederation/flex pull request #927
Opened 2023-04-18 07:44 UTC by mjatin-dev

https://github.com/GluuFederation/flex/issues/919
https://github.com/GluuFederation/flex/issues/918

2023-04-24 10:54 UTC, duttarnab reviewed
1. Set `basic` as `Default Authn Method` on `Authn` page.
2. Visit the `Configuration -->Properties` page. Search `Default Authentication Method`. This field is blank.

2023-04-24 11:01 UTC, duttarnab requested changes

2023-04-24 11:01 UTC, duttarnab commented on admin-ui/app/redux/api/axios.js
> +  timeout: 50000
Please restore the original timeout.

2023-04-24 11:01 UTC, duttarnab commented on admin-ui/app/redux/sagas/LicenseSaga.js
> +      yield put(checkLicensePresentResponse(true))
we cannot set `checkLicensePresentResponse` to `true`. Please restore it to original value.

2023-04-24 11:01 UTC, duttarnab commented on admin-ui/plugins/auth-server/plugin-metadata.js
> -} from 'Utils/PermChecker'
Any reason of replacing single quotes with double quotes?

2023-04-24 11:44 UTC, mjatin-dev commented on admin-ui/plugins/auth-server/plugin-metadata.js
> -} from 'Utils/PermChecker'
Actually by mistake i format that file using prettier. i fixed that and run lint as well.

2023-04-24 11:45 UTC, mjatin-dev commented on admin-ui/plugins/auth-server/plugin-metadata.js
> -} from 'Utils/PermChecker'
Actually by mistake i format that file using prettier. i fixed that and run lint as well.

2023-04-24 12:40 UTC, duttarnab submitted a review, later dismissed

2023-04-25 10:24 UTC, duttarnab approved these changes

2023-04-25 10:24 UTC, merged